version: "3.9"

networks:
  sandbox_net:
    driver: bridge
    internal: true
  internet_net:
    driver: bridge

services:
  squid:
    image: ubuntu/squid:latest
    networks: [sandbox_net, internet_net]
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
    ports:
      - "3128:3128"

  tooling-sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-assistant-sandbox:latest
    container_name: tooling-sandbox
    user: claude
    env_file:
      - .env
    volumes:
      - ./claude-config/claude.json:/home/claude/.claude.json
      - ./claude-config/.claude:/home/claude/.claude
      - ~/.gemini:/home/claude/.gemini
      - ~/.talon/user/jackt:/home/claude/devai/talon
      - ~/dev/ai/cursor-rules:/home/claude/devai/cursor-rules
      - ~/dev/ai/assistant-sandbox:/home/claude/devai/assistant-sandbox
      - ~/dev/ai/ai-notes/sandbox:/home/claude/devai/ai-notes/sandbox
      - ./sandbox-instructions/tooling-claude.md:/home/claude/devai/CLAUDE.md
    environment:
      - NODE_ENV=development
    working_dir: /home/claude/devai
    command: tail -f /dev/null

  restricted-sandbox:
    image: ai-assistant-sandbox:latest
    container_name: restricted-sandbox
    user: claude
    networks: [sandbox_net]
    env_file:
      - .env
    volumes:
      - ./claude-config/claude.json:/home/claude/.claude.json
      - ./claude-config/.claude:/home/claude/.claude
      - ~/.gemini:/home/claude/.gemini
      - ~/dev/ai/assistant-sandbox:/home/claude/devai/assistant-sandbox
      - ~/dev/ai/ai-notes/sandbox:/home/claude/devai/ai-notes/sandbox
      - ./sandbox-instructions/tooling-claude.md:/home/claude/devai/CLAUDE.md
    environment:
      - NODE_ENV=development
      - HTTP_PROXY=http://squid:3128
      - HTTPS_PROXY=http://squid:3128
      - NO_PROXY=localhost,127.0.0.1,squid,tooling-sandbox,restricted-sandbox,172.30.0.0/16
    working_dir: /home/claude/devai
    command: tail -f /dev/null
