version: "3.9"

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          ip_range: 172.22.0.0/24
  internet_net:
    driver: bridge

services:
  dns:
    image: strm/dnsmasq@sha256:dcf4c0aeb69ea6b9bca81314449d732ecd2ea021588d8a34d4be7c2304f89a39
    container_name: dns
    cap_add:
      - NET_ADMIN
    networks:
      internal:
        ipv4_address: 172.22.0.10
      internet_net: {}
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    entrypoint: ["sh", "-c", "syslogd && dnsmasq && tail -f /var/log/messages"]

  tooling-sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-assistant-sandbox:latest
    container_name: tooling-sandbox
    user: claude
    networks:
      - internet_net
    env_file:
      - .env
    volumes:
      - ./claude-config/claude.json:/home/claude/.claude.json
      - ./claude-config/.claude:/home/claude/.claude
      - ~/.gemini:/home/claude/.gemini
      - ~/.talon/user/jackt:/home/claude/devai/talon
      - ~/dev/ai/cursor-rules:/home/claude/devai/cursor-rules
      - ~/dev/ai/assistant-sandbox:/home/claude/devai/assistant-sandbox
      - ~/dev/ai/ai-notes/sandbox:/home/claude/devai/ai-notes/sandbox
      - ./sandbox-instructions/tooling-claude.md:/home/claude/devai/CLAUDE.md
      - ./shell-history/tooling-sandbox-history:/home/claude/.bash_history
    working_dir: /home/claude/devai
    command: tail -f /dev/null

  restricted-sandbox:
    image: ai-assistant-sandbox:latest
    container_name: restricted-sandbox
    user: claude
    networks:
      - internal
      - internet_net
    dns: 172.22.0.10
    env_file:
      - .env
    volumes:
      - ./claude-config/claude.json:/home/claude/.claude.json
      - ./claude-config/.claude:/home/claude/.claude
      - ~/.gemini:/home/claude/.gemini
      - ~/dev/ai/assistant-sandbox:/home/claude/devai/assistant-sandbox
      - ~/dev/ai/ai-notes/sandbox:/home/claude/devai/ai-notes/sandbox
      - ./sandbox-instructions/tooling-claude.md:/home/claude/devai/CLAUDE.md
      - ./shell-history/restricted-sandbox-history:/home/claude/.bash_history
    working_dir: /home/claude/devai
    command: tail -f /dev/null

  workspace1-claude:
    image: ai-assistant-sandbox:latest
    container_name: workspace1-claude
    user: claude
    networks:
      - internal
      - internet_net
    dns: 172.22.0.10
    env_file:
      - .env
    volumes:
      - ./claude-config/claude.json:/home/claude/.claude.json
      - ./claude-config/.claude:/home/claude/.claude
      - ~/.gemini:/home/claude/.gemini
      - ~/dev/workspace1:/home/claude/devai/workspace1
      - ~/dev/drm/tooling/rm-utilities:/home/claude/devai/rm-utilities
      - ./sandbox-instructions/workspace1-claude.md:/home/claude/devai/CLAUDE.md
      - ./shell-history/workspace1-claude-history:/home/claude/.bash_history
    working_dir: /home/claude/devai
    command: tail -f /dev/null
